% Multiscale energetics in Bhalachandran et al. (2020, JAS).
% A1, A2, A5 and A6 follow the cylindrical pressure-coordinate appendix.
% A3/A4 convention is selected explicitly in TC_KEBG_config. u/v are
% radial/tangential winds.
clear
clc
Run_dir = ['../']; addpath(Run_dir); start

cfg = TC_KEBG_config;
Data_dir = [pwd,'/Result/azimuthally'];
Save_dir = [pwd,'/Result/KEBG']; mkdir(Save_dir)
T_beg = datenum(cfg.Time_beg); T_end = datenum(cfg.Time_end);
T_frq = cfg.Time_frq/1440;
plev = cfg.calc.Pressure_levels_hPa(:)*100; % Pa, descending
radius_limit = cfg.calc.Budget_Radius*1000;
Cp = cfg.calc.Cp; Rd = cfg.calc.Rd; g = 9.81;
if cfg.calc.Run_self_test, self_test(Cp,Rd); end

for TIME = T_beg:T_frq:T_end
    [yy,mm,dd,hh,mi,ss] = date2str(TIME);
    T_name = [yy,'-',mm,'-',dd,'_',hh,':',mi,':',ss];
    hit = dir([Data_dir,'/',cfg.Save_nam,'*',T_name,'.mat']);
    if isempty(hit), continue, end
    file_in = [Data_dir,'/',hit(1).name];
    fprintf('\nDate: %s\n',T_name)

    % Inputs must have been regenerated by TC_KEBG_mvct/azimuthally.
    R = load_data(file_in,'R'); PHI = load_data(file_in,'PHI');
    u = load_data(file_in,'u'); v = load_data(file_in,'v');
    p_native = load_data(file_in,'p');
    if isempty(p_native), p_native = load_data(file_in,'P')*100; end
    omega = load_data(file_in,'omega');
    T = load_data(file_in,'tk'); theta = load_data(file_in,'theta');
    H = load_data(file_in,'H_DIABATIC');
    validate_cylindrical_inputs(p_native,u,v,omega,T,theta,H,file_in);
    lon_TC = load_data(file_in,'lon_TC'); lat_TC = load_data(file_in,'lat_TC');
    lon_track = load_data(file_in,'lon_track'); lat_track = load_data(file_in,'lat_track');
    center_slp = load_data(file_in,'center_slp'); slp_track = load_data(file_in,'slp_track');
    swd_track = load_data(file_in,'swd_track');
    heating_components_available = load_data(file_in,'heating_components_available');
    u_TC = load_data(file_in,'u_TC'); v_TC = load_data(file_in,'v_TC');
    center_motion_method = load_data(file_in,'center_motion_method');

    % The paper uses storm-centred cylindrical ISOBARIC coordinates.
    [u,v,omega,T,theta,H] = to_isobaric(plev,p_native,u,v,omega,T,theta,H);
    r = R(:)'*1000;
    % Exclude the Nyquist harmonic: it has no distinct negative partner
    % and cannot be represented by the F_ab(n) pair without double counting.
    max_wn = min(floor((numel(PHI)-1)/2),cfg.calc.Max_WN);
    WN = 0:max_wn;
    fprintf('Calculating A1--A6 for WN 0--%d ...\n',max_wn)

    % Fourier coefficients at every (p,r); fields are [p, phi, r].
    if cfg.calc.Heating_is_theta_tendency
        H = (T./theta).*H; % dT/dt at fixed p, K s-1
    end
    C = make_coefficients(u,v,omega,T,H,numel(PHI));
    if any(~C.valid_column(:))
        warning('TC_KEBG:IncompleteAzimuth',...
            '%d (p,r) columns have incomplete azimuthal coverage and are excluded from spectral diagnostics.',...
            nnz(~C.valid_column));
    end
    [gamma,Tbar,Hbar,omegabar] = static_stability(theta,T,H,omega,plev,r,Rd,Cp);
    dm = isobaric_mass(plev,r,radius_limit,g);
    [ape_factor,APE_convention] = ape_normalization(cfg.calc.APE_convention,Cp);
    azimuth_valid_column = C.valid_column;

    [KE,APE,A1,A2,A2_m_low,A2_m_high,A2_triad,A2_m_WN,A3,A4,A5,A6] = spectral_budgets(C,gamma,Tbar,Hbar,...
        omegabar,plev,r,WN,Cp,ape_factor,radius_limit,cfg.calc.Save_full_triad_tensor,cfg.calc.Triad_precision);
    A2_target_WN = WN(WN>0);
    A2_k_WN = repmat(A2_target_WN(:),1,numel(A2_m_WN))-repmat(A2_m_WN(:)',numel(A2_target_WN),1);

    KE_int = domain_mean_by_wn(KE,dm); APE_int = domain_mean_by_wn(APE,dm);
    A1_int = domain_mean_by_wn(A1,dm); A2_int = domain_mean_by_wn(A2,dm);
    A2_m_low_int = domain_mean_by_wn(A2_m_low,dm); A2_m_high_int = domain_mean_by_wn(A2_m_high,dm);
    A3_int = domain_mean_by_wn(A3,dm); A4_int = domain_mean_by_wn(A4,dm);
    A5_int = domain_mean_by_wn(A5,dm); A6_int = domain_mean_by_wn(A6,dm);
    group_name = {'WN0','WN1_2','WN3_plus','WN_all'};
    group_index = {find(WN==0),find(WN>=1 & WN<=2),find(WN>=3),find(WN>=0)};
    KE_group = group_sum(KE_int,group_index); APE_group = group_sum(APE_int,group_index);
    A1_group = group_sum(A1_int,group_index); A2_group = group_sum(A2_int,group_index);
    A2_m_low_group = group_sum(A2_m_low_int,group_index); A2_m_high_group = group_sum(A2_m_high_int,group_index);
    A3_group = group_sum(A3_int,group_index); A4_group = group_sum(A4_int,group_index);
    A5_group = group_sum(A5_int,group_index); A6_group = group_sum(A6_int,group_index);

    % Compatibility aliases retain the original downstream naming.
    APE_gen = A3 + A4; APE_to_KE = A5 + A6;
    BT_0_to_n = A1; EE_to_n = A2;
    A1_WN0 = -sum(A1(:,:,2:end),3,'omitnan');
    A1_WN0(:,1) = NaN;
    A1_WN0_int = domain_mean_by_wn(reshape(A1_WN0,size(A1_WN0,1),size(A1_WN0,2),1),dm);
    A1_exchange_closure = A1_WN0_int + sum(A1_int(2:end),'omitnan');
    if cfg.calc.Diagnose_equation_closure
        [KE_tendency,APE_tendency,Tendency_scheme,Tendency_dt_s] = energy_tendency(...
            TIME,T_frq,Data_dir,cfg,plev,r,WN,Cp,Rd,radius_limit,ape_factor,KE,APE);
        [KE_rhs,APE_rhs] = resolved_energy_rhs(A1_WN0,A1,A2,A3,A4,A5,A6);
        KE_residual = KE_tendency-KE_rhs;
        APE_residual = APE_tendency-APE_rhs;
        Closure_definition='finite_difference_tendency_minus_A1_to_A6_pathways';
    else
        KE_tendency=NaN(size(KE)); APE_tendency=KE_tendency;
        KE_rhs=KE_tendency; APE_rhs=KE_tendency;
        KE_residual=KE_tendency; APE_residual=KE_tendency;
        Tendency_scheme='disabled'; Tendency_dt_s=NaN;
        Closure_definition='disabled';
    end
    KE_tendency_int=domain_mean_by_wn(KE_tendency,dm); APE_tendency_int=domain_mean_by_wn(APE_tendency,dm);
    KE_rhs_int=domain_mean_by_wn(KE_rhs,dm); APE_rhs_int=domain_mean_by_wn(APE_rhs,dm);
    KE_residual_int=domain_mean_by_wn(KE_residual,dm); APE_residual_int=domain_mean_by_wn(APE_residual,dm);
    KE_tendency_group=group_sum(KE_tendency_int,group_index); APE_tendency_group=group_sum(APE_tendency_int,group_index);
    KE_rhs_group=group_sum(KE_rhs_int,group_index); APE_rhs_group=group_sum(APE_rhs_int,group_index);
    KE_residual_group=group_sum(KE_residual_int,group_index); APE_residual_group=group_sum(APE_residual_int,group_index);
    Save_file = [cfg.Save_nam,'_',T_name,'.mat'];
    save([Save_dir,'/',Save_file],...
      'TIME','R','PHI','r','plev','WN','radius_limit','Cp','Rd','g',...
      'gamma','Tbar','Hbar','omegabar','dm','H','APE_convention','ape_factor','azimuth_valid_column',...
      'KE','APE','A1','A2','A2_m_low','A2_m_high','A2_triad','A2_target_WN','A2_m_WN','A2_k_WN','A3','A4','A5','A6','APE_gen','APE_to_KE','BT_0_to_n','EE_to_n',...
      'A1_WN0','A1_WN0_int','A1_exchange_closure',...
      'KE_int','APE_int','A1_int','A2_int','A2_m_low_int','A2_m_high_int','A3_int','A4_int','A5_int','A6_int',...
      'KE_tendency','APE_tendency','KE_rhs','APE_rhs','KE_residual','APE_residual','Tendency_scheme','Tendency_dt_s','Closure_definition',...
      'KE_tendency_int','APE_tendency_int','KE_rhs_int','APE_rhs_int','KE_residual_int','APE_residual_int',...
      'group_name','group_index','KE_group','APE_group','A1_group','A2_group',...
      'A2_m_low_group','A2_m_high_group','A3_group','A4_group','A5_group','A6_group',...
      'KE_tendency_group','APE_tendency_group','KE_rhs_group','APE_rhs_group','KE_residual_group','APE_residual_group',...
      'lon_TC','lat_TC','lon_track','lat_track','center_slp','slp_track','swd_track',...
      'u_TC','v_TC','center_motion_method','heating_components_available','-v7.3')
end

function [u,v,o,T,th,H] = to_isobaric(plev,p,u,v,o,T,th,H)
% Interpolate every cylindrical column to fixed pressure; no height-coordinate
% approximation is retained.  p must be Pa and variables native mass levels.
np = numel(plev); nphi = size(p,2); nr = size(p,3);
uI = NaN(np,nphi,nr); vI=uI; oI=uI; TI=uI; thI=uI; HI=uI;
for j=1:nphi
 for ir=1:nr
   pp=squeeze(p(:,j,ir)); ok=isfinite(pp);
   if nnz(ok)<2, continue, end
   [pp,ix]=sort(pp(ok)); [pp,ia]=unique(pp,'stable'); ix=ix(ia);
   if numel(pp)<2, continue, end
   uI(:,j,ir)=interp1(pp,sorted_column(u(:,j,ir),ok,ix),plev,'linear',NaN);
   vI(:,j,ir)=interp1(pp,sorted_column(v(:,j,ir),ok,ix),plev,'linear',NaN);
   oI(:,j,ir)=interp1(pp,sorted_column(o(:,j,ir),ok,ix),plev,'linear',NaN);
   TI(:,j,ir)=interp1(pp,sorted_column(T(:,j,ir),ok,ix),plev,'linear',NaN);
   thI(:,j,ir)=interp1(pp,sorted_column(th(:,j,ir),ok,ix),plev,'linear',NaN);
   HI(:,j,ir)=interp1(pp,sorted_column(H(:,j,ir),ok,ix),plev,'linear',NaN);
 end
end

function q = sorted_column(q,ok,ix)
q=q(ok); q=q(ix);
end
u=uI; v=vI; o=oI; T=TI; th=thI; H=HI;
end

function validate_cylindrical_inputs(p,u,v,o,T,th,H,fileName)
required = {u,v,o,T,th,H};
for k=1:numel(required)
    assert(isequal(size(required{k}),size(p)),...
        'TC_KEBG:InputShape','All fields must have the same [level,phi,r] dimensions: %s',fileName)
end
median_p = median(p(isfinite(p)),'omitnan');
assert(isfinite(median_p) && median_p>5e3 && median_p<1.2e5,...
    'TC_KEBG:PressureUnits','Pressure must be in Pa after azimuthal remapping: %s',fileName)
assert(all(T(isfinite(T))>0) && all(th(isfinite(th))>0),...
    'TC_KEBG:ThermodynamicUnits','Temperature and potential temperature must be positive Kelvin: %s',fileName)
end

function C = make_coefficients(u,v,o,T,H,nphi)
% Do not manufacture asymmetries by filling gaps. A spectral column is used
% only when every required azimuthal sample is finite.
valid = all(isfinite(u) & isfinite(v) & isfinite(o) & isfinite(T) & isfinite(H),2);
u(~isfinite(u))=0; v(~isfinite(v))=0; o(~isfinite(o))=0;
T(~isfinite(T))=0; H(~isfinite(H))=0;
C.u = fft(u,[],2)/nphi; C.v = fft(v,[],2)/nphi;
C.o = fft(o,[],2)/nphi; C.T = fft(T,[],2)/nphi;
C.H = fft(H,[],2)/nphi;
for name = {'u','v','o','T','H'}
    q=C.(name{1}); q=repmat(valid,1,nphi,1).*q; q(~repmat(valid,1,nphi,1))=NaN; C.(name{1})=q;
end
C.N = floor((nphi-1)/2); C.nphi=nphi; C.valid_column=squeeze(valid);
end

function [gam,Tm,Hm,om] = static_stability(th,T,H,o,p,r,Rd,Cp)
Tm=squeeze(real(mean(T,2,'omitnan'))); Hm=squeeze(real(mean(H,2,'omitnan')));
om=squeeze(real(mean(o,2,'omitnan'))); thm=squeeze(real(mean(th,2,'omitnan')));
dthdp=deriv_p(thm,p); pp=repmat(p(:),1,numel(r));
gam=-((thm./Tm).*(Rd./(Cp*pp)))./dthdp;
% Negative/zero values do not define a positive-definite dry APE norm.
% Retain their occurrence in the output as NaN rather than silently clipping.
gam(~isfinite(gam) | gam<=0)=NaN;
end

function [factor,label] = ape_normalization(convention,Cp)
switch lower(convention)
 case 'dimensionally_consistent'
   factor=Cp; label='dimensionally_consistent';
 case 'paper_literal'
   factor=1; label='paper_literal';
 otherwise
   error('TC_KEBG:APEConvention','Unknown cfg.calc.APE_convention: %s',convention)
end
end

function [KEt,APEt,scheme,dt_s] = energy_tendency(TIME,dt_day,dataDir,cfg,plev,r,WN,Cp,Rd,radius_limit,apeFactor,KE0,APE0)
% The diagnostic tendency is calculated from the same energy definition and
% fixed (p,r,WN) grid used for the current output.
[KEb,APEb,has_b] = energy_state_at(TIME-dt_day,dataDir,cfg,plev,r,WN,Cp,Rd,radius_limit,apeFactor);
[KEf,APEf,has_f] = energy_state_at(TIME+dt_day,dataDir,cfg,plev,r,WN,Cp,Rd,radius_limit,apeFactor);
dt_s=dt_day*86400;
if has_b && has_f
    KEt=(KEf-KEb)/(2*dt_s); APEt=(APEf-APEb)/(2*dt_s); scheme='second_order_centered';
elseif has_f
    KEt=(KEf-KE0)/dt_s; APEt=(APEf-APE0)/dt_s; scheme='first_order_forward';
elseif has_b
    KEt=(KE0-KEb)/dt_s; APEt=(APE0-APEb)/dt_s; scheme='first_order_backward';
else
    KEt=NaN(size(KE0)); APEt=NaN(size(APE0)); scheme='unavailable'; dt_s=NaN;
end
end

function [KE,APE,found] = energy_state_at(TIME,dataDir,cfg,plev,r,WN,Cp,Rd,radius_limit,apeFactor)
[yy,mm,dd,hh,mi,ss] = date2str(TIME);
name=[yy,'-',mm,'-',dd,'_',hh,':',mi,':',ss];
hit=dir([dataDir,'/',cfg.Save_nam,'*',name,'.mat']);
found=~isempty(hit); KE=[]; APE=[];
if ~found, return, end
f=[dataDir,'/',hit(1).name];
R=load_data(f,'R'); PHI=load_data(f,'PHI');
assert(isequal(r,R(:)'*1000) && numel(PHI)>=2*max(WN)+1,...
    'TC_KEBG:ClosureGrid','Neighbouring file uses a different cylindrical grid: %s',f)
u=load_data(f,'u'); v=load_data(f,'v'); p=load_data(f,'p');
if isempty(p), p=load_data(f,'P')*100; end
o=load_data(f,'omega'); T=load_data(f,'tk'); th=load_data(f,'theta'); H=load_data(f,'H_DIABATIC');
validate_cylindrical_inputs(p,u,v,o,T,th,H,f);
[u,v,o,T,th,H]=to_isobaric(plev,p,u,v,o,T,th,H);
if cfg.calc.Heating_is_theta_tendency, H=(T./th).*H; end
C=make_coefficients(u,v,o,T,H,numel(PHI));
[gam,~,~,~]=static_stability(th,T,H,o,plev,r,Rd,Cp);
[KE,APE]=spectral_energy(C,gam,plev,r,WN,apeFactor,radius_limit);
end

function [KE,APE] = spectral_energy(C,gam,p,r,WN,apeFactor,radius_limit)
np=size(C.u,1); nr=size(C.u,3); KE=NaN(np,nr,numel(WN)); APE=KE;
T0=squeeze(real(C.T(:,1,:))); Tarea=radial_mean(T0,r,radius_limit);
for q=1:numel(WN)
    n=WN(q); KE(:,:,q)=0.5*(F(C.u,C.u,n,C)+F(C.v,C.v,n,C));
    if n==0
        APE(:,:,q)=0.5*apeFactor*gam.*(T0-repmat(Tarea,1,nr)).^2;
    else
        APE(:,:,q)=0.5*apeFactor*gam.*F(C.T,C.T,n,C);
    end
end
end

function [KErhs,APErhs] = resolved_energy_rhs(A1mean,A1,A2,A3,A4,A5,A6)
% Only pathways represented by Appendix A are on this RHS. Transport,
% friction, diffusion, pressure work and numerical terms remain residual.
KErhs=NaN(size(A1)); APErhs=KErhs;
KErhs(:,:,1)=A1mean+A5(:,:,1);
APErhs(:,:,1)=A3(:,:,1)-A5(:,:,1);
if size(A1,3)>1
    KErhs(:,:,2:end)=A1(:,:,2:end)+A2(:,:,2:end)+A6(:,:,2:end);
    APErhs(:,:,2:end)=A4(:,:,2:end)-A6(:,:,2:end);
end
end

function [KE,APE,A1,A2,A2low,A2high,A2triad,mWN,A3,A4,A5,A6] = spectral_budgets(C,gam,Tm,Hm,om,p,r,WN,Cp,apeFactor,radius_limit,saveTriad,triadPrecision)
np=size(C.u,1); nr=size(C.u,3); nw=numel(WN);
KE=NaN(np,nr,nw); APE=KE; A1=KE; A2=KE; A2low=KE; A2high=KE; A3=KE; A4=KE; A5=KE; A6=KE;
% Exclude both representations of the even-grid Nyquist harmonic.
mWN=-C.N:C.N; mWN(mWN==0)=[];
if saveTriad
    A2triad=NaN(np,nr,nw-1,numel(mWN),triadPrecision);
else
    A2triad=[];
end
% Mean gradients for A1 and the full spectral derivative fields for A2.
ur=squeeze(real(C.u(:,1,:))); vr=squeeze(real(C.v(:,1,:)));
rinv=1./r; rinv(1)=0;
durdr=deriv_r(ur,r); dvrdr=deriv_r(vr,r); durdp=deriv_p(ur,p); dvrdp=deriv_p(vr,p);
Du_phi=phi_derivative(C.u,C); Dv_phi=phi_derivative(C.v,C);
Du_r=fft(deriv_r(ifft(C.u*C.nphi,[],2,'symmetric'),r),[],2)/C.nphi;
Dv_r=fft(deriv_r(ifft(C.v*C.nphi,[],2,'symmetric'),r),[],2)/C.nphi;
Du_p=fft(deriv_p(ifft(C.u*C.nphi,[],2,'symmetric'),p),[],2)/C.nphi;
Dv_p=fft(deriv_p(ifft(C.v*C.nphi,[],2,'symmetric'),p),[],2)/C.nphi;
T0=squeeze(real(C.T(:,1,:))); H0=squeeze(real(C.H(:,1,:))); o0=squeeze(real(C.o(:,1,:)));
Tarea=radial_mean(T0,r,radius_limit); Harea=radial_mean(H0,r,radius_limit); oarea=radial_mean(o0,r,radius_limit);
for q=1:nw
 n=WN(q);
 Fuu=F(C.u,C.u,n,C); Fvv=F(C.v,C.v,n,C);
 KE(:,:,q)=0.5*(Fuu+Fvv);
 if n==0
   APE(:,:,q)=0.5*apeFactor*gam.*(T0-repmat(Tarea,1,nr)).^2;
   A1(:,:,q)=0; A2(:,:,q)=0;
   A2low(:,:,q)=0; A2high(:,:,q)=0;
   A3(:,:,q)=apeFactor*gam.*(H0-repmat(Harea,1,nr)).*(T0-repmat(Tarea,1,nr));
   A4(:,:,q)=0;
   A5(:,:,q)=-Cp./repmat(p(:),1,nr).*(o0-repmat(oarea,1,nr)).*(T0-repmat(Tarea,1,nr));
   A6(:,:,q)=0;
 else
   APE(:,:,q)=0.5*apeFactor*gam.*F(C.T,C.T,n,C);
   Fuvr=F(C.u,C.v,n,C);
   A1(:,:,q)=Fuvr.*dvrdr + F(C.u,C.u,n,C).*durdr ...
        + F(C.v,C.o,n,C).*dvrdp + F(C.u,C.o,n,C).*durdp ...
        + F(C.v,C.v,n,C).*ur.*repmat(rinv,np,1) - Fuvr.*vr.*repmat(rinv,np,1);
   [A2(:,:,q),A2low(:,:,q),A2high(:,:,q),triad_n]=nonlinear_transfer(n,C,r,Du_phi,Dv_phi,Du_r,Dv_r,Du_p,Dv_p,p,mWN,saveTriad,triadPrecision);
   if saveTriad, A2triad(:,:,q-1,:)=reshape(triad_n,np,nr,1,numel(mWN)); end
   A3(:,:,q)=0; A4(:,:,q)=apeFactor*gam.*F(C.H,C.T,n,C);
   A5(:,:,q)=0; A6(:,:,q)=-Cp./repmat(p(:),1,nr).*F(C.o,C.T,n,C);
 end
end
% The cylindrical centre is singular and is excluded from all integrals.
A1(:,1,:)=NaN; A2(:,1,:)=NaN;
A2low(:,1,:)=NaN; A2high(:,1,:)=NaN;
end

function [out,outlow,outhigh,triad] = nonlinear_transfer(n,C,r,Du_phi,Dv_phi,Du_r,Dv_r,Du_p,Dv_p,p,mWN,saveTriad,triadPrecision)
np=size(C.u,1); nr=size(C.u,3); out=zeros(np,nr); outlow=out; outhigh=out; rinv=1./r; rinv(1)=0;
if saveTriad, triad=NaN(np,nr,numel(mWN),triadPrecision); else, triad=[]; end
for im=1:numel(mWN)
 m=mWN(im);
 um=mode(C.u,m,C); vm=mode(C.v,m,C);
 % u is radial and v is tangential.  These are the radial and tangential
 % momentum equations in cylindrical pressure coordinates, dotted with
 % V_r(m) and V_theta(m), respectively.
 trad=Fmn(C.v,Du_phi,m,n,C).*repmat(rinv,np,1) + Fmn(C.u,Du_r,m,n,C) + Fmn(C.o,Du_p,m,n,C) - Fmn(C.v,C.v,m,n,C).*repmat(rinv,np,1);
 ttan=Fmn(C.v,Dv_phi,m,n,C).*repmat(rinv,np,1) + Fmn(C.u,Dv_r,m,n,C) + Fmn(C.o,Dv_p,m,n,C) + Fmn(C.v,C.u,m,n,C).*repmat(rinv,np,1);
 fluxr=vm.*Fmn(C.u,C.v,m,n,C)+um.*Fmn(C.u,C.u,m,n,C);
 fluxp=um.*Fmn(C.o,C.u,m,n,C)+vm.*Fmn(C.o,C.v,m,n,C);
 inc=um.*trad + vm.*ttan - deriv_r(repmat(r,np,1).*fluxr,r).*repmat(rinv,np,1) - deriv_p(fluxp,p);
 out=out+inc;
 if abs(m)<=2, outlow=outlow+inc; else, outhigh=outhigh+inc; end
 if saveTriad
     inc(:,1)=NaN;
     triad(:,:,im)=cast(real(inc),triadPrecision);
 end
end
out=real(out);
outlow=real(outlow); outhigh=real(outhigh);
out(:,1)=NaN;
outlow(:,1)=NaN; outhigh(:,1)=NaN;
end

function out = F(A,B,n,C)
if n==0, out=real(mode(A,0,C).*mode(B,0,C)); else, out=real(mode(A,n,C).*mode(B,-n,C)+mode(A,-n,C).*mode(B,n,C)); end
end
function out = Fmn(A,B,m,n,C)
out=mode(A,n-m,C).*mode(B,-n,C)+mode(A,-n-m,C).*mode(B,n,C);
end
function a = mode(A,k,C)
if abs(k)>C.N, a=zeros(size(A,1),size(A,3)); return, end
if k>=0, ix=k+1; else, ix=C.nphi+k+1; end
a=squeeze(A(:,ix,:));
end
function D = phi_derivative(A,C)
D=A; for k=0:C.N, D(:,k+1,:)=1i*k*A(:,k+1,:); end
for k=1:C.N-1, D(:,C.nphi-k+1,:)=-1i*k*A(:,C.nphi-k+1,:); end
end

function d = deriv_r(a,r)
d=NaN(size(a)); rr=r; rr(1)=0;
if ndims(a)==2
    for k=1:size(a,1), d(k,:)=gradient(a(k,:),rr); end
else
    for k=1:size(a,1)
        for j=1:size(a,2)
            d(k,j,:)=gradient(squeeze(a(k,j,:)),rr);
        end
    end
end
end
function d = deriv_p(a,p)
d=NaN(size(a));
if ndims(a)==2, for j=1:size(a,2), d(:,j)=gradient(a(:,j),p); end
else, for j=1:size(a,2), for k=1:size(a,3), d(:,j,k)=gradient(a(:,j,k),p); end, end, end
end
function q = radial_mean(a,r,radius_limit)
w=r; w(r>radius_limit | ~isfinite(w))=NaN;
q=sum(a.*repmat(w,size(a,1),1),2,'omitnan')./sum(repmat(w,size(a,1),1).*(isfinite(a)),2,'omitnan');
end
function dm = isobaric_mass(p,r,rlim,g)
dp=abs(gradient(p)); edge=[0,0.5*(r(1:end-1)+r(2:end)),r(end)+0.5*(r(end)-r(end-1))];
area=pi*(edge(2:end).^2-edge(1:end-1).^2); area(1)=NaN; area(r>rlim)=NaN;
dm=repmat(dp(:)/g,1,numel(r)).*repmat(area,numel(p),1);
end
function out = domain_mean_by_wn(x,dm)
out=NaN(1,size(x,3)); for n=1:size(x,3), q=x(:,:,n); out(n)=sum(q(:).*dm(:),'omitnan')/sum(dm(:).*isfinite(q(:)),'omitnan'); end
end
function out = group_sum(x,idx)
out=NaN(1,numel(idx)); for k=1:numel(idx), out(k)=sum(x(idx{k}),'omitnan'); end
end

function self_test(Cp,Rd)
% Analytic invariants: axisymmetric flow has no eddy transfer; a cosine
% harmonic has the one-sided Parseval energy Cp*gamma*a^2/4.
nphi=8; p=[100000;90000;80000]; r=[0 1000 2000];
z=zeros(numel(p),nphi,numel(r)); C=make_coefficients(z,z,z,z,z,nphi);
gam=ones(numel(p),numel(r))*1e-3; mean0=zeros(numel(p),numel(r));
[~,~,A1,A2,~,~,~,~,~,~,~,~]=spectral_budgets(C,gam,mean0,mean0,mean0,p,r,0:3,Cp,Cp,2000,false,'single');
assert(all(abs(A1(:))<1e-12 | isnan(A1(:))),'A1 axisymmetric invariant failed')
assert(all(abs(A2(:))<1e-12 | isnan(A2(:))),'A2 axisymmetric invariant failed')
a=2; T=repmat(reshape(a*cos((0:nphi-1)*2*pi/nphi),1,nphi,1),numel(p),1,numel(r));
C=make_coefficients(z,z,z,T,z,nphi); [~,APE]=spectral_budgets(C,gam,mean0,mean0,mean0,p,r,0:3,Cp,Cp,2000,false,'single');
assert(max(abs(APE(:,:,2)-0.25*Cp*gam*a^2),[],'all','omitnan')<1e-10,'APE Parseval invariant failed')
u=repmat(reshape(cos((0:nphi-1)*2*pi/nphi),1,nphi,1),numel(p),1,numel(r));
v=repmat(reshape(sin((0:nphi-1)*2*pi/nphi),1,nphi,1),numel(p),1,numel(r));
C=make_coefficients(u,v,z,z,z,nphi); [~,~,~,A2,A2low,A2high,A2triad,mWN]=spectral_budgets(C,gam,mean0,mean0,mean0,p,r,0:3,Cp,Cp,2000,true,'single');
assert(max(abs(A2-A2low-A2high),[],'all','omitnan')<1e-10,'A2 m-group partition failed')
assert(size(A2triad,4)==numel(mWN),'A2 triad tensor index failed')
assert(max(abs(A2(:,:,2:end)-sum(double(A2triad),4,'omitnan')),[],'all','omitnan')<1e-6,'A2 triad reconstruction failed')
[kr,ar]=resolved_energy_rhs(ones(3,3),ones(3,3,2),2*ones(3,3,2),3*ones(3,3,2),4*ones(3,3,2),5*ones(3,3,2),6*ones(3,3,2));
assert(all(kr(:,:,1)==6,'all') && all(ar(:,:,1)==-2,'all') && ...
       all(kr(:,:,2)==9,'all') && all(ar(:,:,2)==-2,'all'),'Closure RHS partition failed')
assert(Rd>0,'Gas constant must be positive')
end
